#define mcu_stm32_h7 1
#define freertos 1
#define rtthread 0
#define INPUT_USE_KEYPAD 0
#define keypad_row 4
#define keypad_col 4
#define keypad_row1 GPIOA,GPIO_PIN_1
#define keypad_row2 GPIOA,GPIO_PIN_1
#define keypad_row3 GPIOA,GPIO_PIN_1
#define keypad_row4 GPIOA,GPIO_PIN_1
#define keypad_col1 GPIOA,GPIO_PIN_1
#define keypad_col2 GPIOA,GPIO_PIN_1
#define keypad_col3 GPIOA,GPIO_PIN_1
#define keypad_col4 GPIOA,GPIO_PIN_1
#define DISPLAY_USE_R61408 1
#define DISPLAY_USE_SSD1306 0
#define drv_pwm 1
#define drv_spi 1
#define drv_iic 1
