#define mcu_stm32_h7 1
#define freertos 1
#define rtthread 0
#define use_Ads1112 0
#define INPUT_USE_KEYPAD 0
#define keypad_row 4
#define keypad_col 4
#define keypad_row1 GPIOA,GPIO_PIN_1
#define keypad_row2 GPIOA,GPIO_PIN_1
#define keypad_row3 GPIOA,GPIO_PIN_1
#define keypad_row4 GPIOA,GPIO_PIN_1
#define keypad_col1 GPIOA,GPIO_PIN_1
#define keypad_col2 GPIOA,GPIO_PIN_1
#define keypad_col3 GPIOA,GPIO_PIN_1
#define keypad_col4 GPIOA,GPIO_PIN_1
#define DISPLAY_USE_R61408 1
#define R61408_SPI_DCLK GPIOB,GPIO_PIN_7
#define R61408_SPI_SDA GPIOB,GPIO_PIN_6
#define R61408_SPI_CS GPIOE,GPIO_PIN_3
#define R61408_RST GPIOE,GPIO_PIN_2
#define UseRgbScreen 1
#define DISPLAY_USE_SSD1963 0
#define DISPLAY_USE_SSD1306 0
#define using_tiny_usb 1
#define tiny_usb_cdc_cnt 2
#define tiny_usb_cdc_demo 0
#define drv_sdram 1
#define drv_pwm 1
#define drv_ltdc 1
#define drv_spi 1
#define drv_iic 1
